variables:
  REGISTRY_URL: docker.infra.cloveri.com
  REPOSITORY_PATH: cloveri.start/step/configs_service
  IMAGE: cfs_prod:latest

build_image:
 tags:
   - docker
 image: docker:27.3.1
 services:
  - docker:27.3.1-dind
 variables:
  DOCKER_TLS_CERTDIR: "/certs"
 before_script:
  - echo "$CI_DEPLOY_PASSWORD" | docker login $REGISTRY_URL -u $CI_DEPLOY_USER --password-stdin
 script:
  - docker build -t $REGISTRY_URL/$REPOSITORY_PATH/$IMAGE .
  - docker push $REGISTRY_URL/$REPOSITORY_PATH/$IMAGE
 rules:
  - if: $CI_COMMIT_BRANCH == "master"
