variables:
  REGISTRY_PATH: docker.infra.cloveri.com
  IMAGE: cloveri.start/step/configs_service

build_image:
 tags:
   - docker
 image: docker:27.3.1
 services:
  - docker:27.3.1-dind
 variables:
  DOCKER_TLS_CERTDIR: "/certs"
 before_script:
  - echo "$CI_DEPLOY_PASSWORD" | docker login $REGISTRY_PATH -u $CI_DEPLOY_USER --password-stdin
 script:
  - docker build -t $REGISTRY_PATH/$IMAGE .
  - docker push $REGISTRY_PATH/$IMAGE
 rules:
  - if: $CI_COMMIT_BRANCH == "master"
